### ISSUE TITLE
Is this plugin current for 0.14.15 (Jun 2022)

### ISSUE THREAD

**Issue by drpradeepharish** [DahaWong/obsidian-footlinks#8]
Hi there

Is this plugin working for the current version (after live-preview) was implemented? If not, is this still being supported?

Thank you

**Comment by berot3** [comment]
I just tested it current obisidian. it doesnt do anything.

```
main.ts:61 Uncaught TypeError: source.get is not a function
    at FootlinksPlugin.generateFootlinks (main.ts:61:32)
    at Object.callback (main.ts:33:25)
    at BB (app.js:1:1464176)
    at t.onChooseItem (app.js:1:1706189)
    at t.eval (plugin:hotkey-helper:1:8424)
    at t.i [as onChooseItem] (plugin:hotkey-helper:1:834)
    at t.onChooseSuggestion (app.js:1:1561562)
    at t.selectSuggestion (app.js:1:1561112)
    at e.useSelectedItem (app.js:1:1515204)
    at Object.func (app.js:1:1513919)
FootlinksPlugin.generateFootlinks @ main.ts:61
callback @ main.ts:33
BB @ app.js:1
t.onChooseItem @ app.js:1
eval @ plugin:hotkey-helper:1
i @ plugin:hotkey-helper:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-front-matter-title-plugin:37 explorer false
```

is displayed in console and

```
main.ts:61 Uncaught TypeError: source.get is not a function
    at FootlinksPlugin.generateFootlinks (main.ts:61:32)
    at HTMLDivElement.eval (main.ts:26:10)
FootlinksPlugin.generateFootlinks @ main.ts:61
eval @ main.ts:26

```
