### ISSUE TITLE
[Feature] Command to process only a single links in selected text

### ISSUE THREAD

**Issue by huyz** [DahaWong/obsidian-footlinks#9]
I would only like to perform the transformation on selected text, not the entire note.

**Comment by mathisgauthey** [comment]
Hi, so you managed to make it work ? The plugin doesn't seem to work with my Obsidian.

**Comment by huyz** [comment]
I tried it many versions ago.  It did work then.

In the current version, it fails with:
```
Uncaught TypeError: source.get is not a function
    at FootlinksPlugin.generateFootlinks (plugin:footlinks:190:36)
    at Object.callback (plugin:footlinks:150:66)
    at yH (app.js:1:1672614)
    at t.onChooseItem (app.js:1:1719005)
    at t.eval (plugin:hotkey-helper:1:8501)
    at t.a [as onChooseItem] (plugin:hotkey-helper:1:834)
    at t.onChooseSuggestion (app.js:1:1522752)
    at t.selectSuggestion (app.js:1:1522302)
    at e.useSelectedItem (app.js:1:1402632)
    at Object.func (app.js:1:1401436)
```

So yeah could be broken for you too
